GET http://localhost:3008/api/word_game?sentence=Same old, just a different day

###
GET https://bootcamp-apis-o6lh.onrender.com/api/totalPhoneBill?bill=sms,call,sms,call

###
POST http://localhost:3008/api/enough
Content-Type: application/json

{
    "usage": "call,sms,call",
    "available" : 54
}

###
POST https://bootcamp-apis-o6lh.onrender.com/api/phoneBill/total
Content-Type: application/json

{
    "bill": "call,sms,call"
}

###
GET https://bootcamp-apis-o6lh.onrender.com/api/phonebill/prices

###
POST http://localhost:3008/api/phoneBill/price
Content-Type: application/json

{
    "type" : "sms",
    "price" : 2.85
}